---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  labels:
    app.kubernetes.io/name: pokedex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pokedex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pokedex
    spec:
      containers:
        - name: pokedex
          image: pokedex
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
